social:
    facebook:
        url:
    twitter:
        url:
    youtube:
        url:
    pinterest:
        url:
    flickr:
        url:
    instagram:
        url:
    rss:
        url:
address:
privacy_policy:
    url:
tollfree:
logo:
    url:
    alt:
    link:
copyright:
    name:
    year:
theme: missioninn