<?php
	require_once(__DIR__.'/shortcodes/accordion.php');
	require_once(__DIR__.'/shortcodes/carousel.php');
	require_once(__DIR__.'/shortcodes/custom-template.php');
	require_once(__DIR__.'/shortcodes/tabs.php');
	require_once(__DIR__.'/shortcodes/email.php');
	require_once(__DIR__.'/shortcodes/ajax.php');
	require_once(__DIR__.'/shortcodes/twig.php');
	require_once(__DIR__.'/shortcodes/feature-image.php');
	require_once(__DIR__.'/shortcodes/gallery.php');
	require_once(__DIR__.'/shortcodes/link.php');
	require_once(__DIR__.'/shortcodes/page-gallery.php');
?>
