social:        
    facebook:
        url: https://www.facebook.com/
        icon:
            inner: fa-facebook-f
            outer: fa-circle
    twitter:
        url: https://twitter.com/
        icon:
            inner: fa-twitter
            outer: fa-circle
    googleplus:
        url: https://plus.google.com/
        icon:
            inner: fa-google-plus
            outer: fa-circle
    youtube:
        url: https://www.youtube.com/user/
        icon:
            inner: fa-youtube
            outer: fa-circle        
    pinterest:
        url: https://www.pinterest.com/
        icon:
            inner: fa-pinterest-p
            outer: fa-circle       
   
    instagram:
        url: https://www.instagram.com/
        icon:
            inner: fa-instagram
            outer: fa-circle       

                   
        
company:
    name:
    address:
        street: Dallas Road
        city: 'Victoria'
        province: BC
        postal: V8Y 4X4
        country: Canada
phone:
    reservations: 866.000.0000
    toll: 866.000.0000
    resort: 000.000.0000
    office: 000.000.0000   
    
    
email:
    info: webmaster@fifthgeardev.com.com
    
settings:
    slideshow:
        home:
            template: 'slideshow-home'
        logo:
            url: 
            alt: Logo
            
    footer:
        grid:
            left:  col-lg-6 col-lg-push-6 
            right: col-lg-6 col-lg-pull-6
        logo:
            url: 
            alt:
        social:
            enable: true
            
    copyright:
        grid:
            left:  col-lg-6 col-lg-push-6 
            right: col-lg-6 col-lg-pull-6
        text: ', Fifth Gear Marketing'
        year: 2016
    modal:
        logo: 
        
forms:
    footer:
        
awards:
    -
        title : 'Sample Award'
        award : 'Award Company'
    -
        title : 'Sample Award Two'
        award : 'Award Company Two'
        
        
specials:
    -
        active : false
        title: 
        details : 
        valid : 
        link : 
        img : 
        animation : data-wow-offset="10"
        class : fg-wow slideInLeft  li-sm-50
        style :        

slideshow:
    home:
        id : homepage-slideshow
        controls : false
        indicators : true
        captions : false
        titles : false
        interval: 6000
        outer_class : feature-carousel carousel-fade
        items:
            -
                title : 
                url : 
                images: 
                    xl : 
                    md : 
                    sm : 
                    xxs : 
                
     